# -*- python -*-

env = Environment(CXXFLAGS=["-g", "-O2", "-Wall", "-ansi", "-pedantic"],
                  CPPPATH=["-Isrc/"],
                  LIBS=["guile"])
    
env.ParseConfig("pkg-config --cflags --libs " +
                "clanCore-1.0 " +
                "clanApp-1.0 " +
                "clanDisplay-1.0 " +
                "clanGL-1.0 " +
                "clanSound-1.0 " +
                "clanMikMod-1.0 " +
                "clanVorbis-1.0 | sed 's/-I/-isystem/'")

env.Command("src/scripting/feuerkraft_wrap.cpp", "src/scripting/feuerkraft.i",
            "swig -guile -c++  -o $TARGET $SOURCE")

env.Program("feuerkraft", [
    "src/editor/editor.cpp",

    "src/buildings/ammotent.cpp", 
    "src/buildings/building.cpp", 
    "src/buildings/building_manager.cpp", 
    "src/buildings/building_map.cpp", 
    "src/buildings/building_map_data.cpp", 
    "src/buildings/building_type_manager.cpp", 
    "src/buildings/custom_building.cpp", 
    "src/buildings/fuelstation.cpp", 
    "src/buildings/headquarter.cpp", 
    "src/buildings/tower.cpp", 
    "src/buildings/tower_ai.cpp", 
    "src/buildings/wall.cpp", 
    "src/buildings/wall_door.cpp", 
    
    "src/vehicles/tank.cpp",
    "src/vehicles/helicopter.cpp",
    "src/vehicles/jeep.cpp",
    "src/vehicles/turret.cpp",
    "src/vehicles/rotor.cpp",
    "src/vehicles/vehicle.cpp",
    "src/generic/random.cpp",
    
    
    "src/input/axis_button.cpp", 
    "src/input/axis_factory.cpp", 
    "src/input/button_axis.cpp", 
    "src/input/button_factory.cpp", 
    "src/input/controller.cpp", 
    "src/input/input_axis_input_device.cpp", 
    "src/input/input_button_input_device.cpp", 
    "src/input/input_manager.cpp", 
    "src/input/input_manager_custom.cpp", 
    "src/input/input_manager_impl.cpp", 
    "src/input/input_manager_player.cpp", 
    "src/input/input_recorder.cpp", 
    "src/input/multi_button.cpp",
    "src/particles/fire_particle.cpp",
    "src/particles/fire_emitter.cpp",
    "src/particles/rocket_smoke_particle.cpp",
    "src/particles/smoke_emitter.cpp",

    "src/scripting/ai_commands.cpp",
    "src/scripting/ai_vehicle_commands.cpp",
    "src/scripting/building_commands.cpp",
    "src/scripting/clanlib_commands.cpp",
    "src/scripting/comm_commands.cpp",
    "src/scripting/debug_commands.cpp",
    "src/scripting/display_commands.cpp",
    "src/scripting/effect_commands.cpp",
    "src/scripting/feuerkraft_wrap.cpp",
    "src/scripting/game_commands.cpp",
    "src/scripting/gameobj_commands.cpp",
    "src/scripting/input_commands.cpp",
    "src/scripting/menu_commands.cpp",
    "src/scripting/object_commands.cpp",
    "src/scripting/player_commands.cpp",
    "src/scripting/script_helper.cpp",
    "src/scripting/sequence_commands.cpp",
    "src/scripting/sound_commands.cpp",
    "src/scripting/trigger_commands.cpp",
    "src/scripting/vehicle_commands.cpp",
    
    "src/sound/sound.cpp",
    "src/sound/sound_dummy.cpp",
    "src/sound/sound_real.cpp",
    "src/sound/sound_res_mgr.cpp",

    "src/groundmap/grid_map.cpp", 
    "src/groundmap/grid_map_data.cpp", 
    "src/groundmap/grid_tile.cpp", 
    "src/groundmap/grid_tile_data.cpp", 
    "src/groundmap/grid_tile_generator.cpp", 
    "src/groundmap/ground_map_data.cpp", 
    "src/groundmap/ground_map_data_factory.cpp", 
    "src/groundmap/ground_type.cpp", 
    "src/groundmap/multi_ground_map.cpp", 
    "src/groundmap/multi_ground_map_data.cpp", 
    "src/groundmap/sprite_tile.cpp", 
    "src/groundmap/sprite_tile_data.cpp", 
    "src/groundmap/tile_data_factory.cpp", 
    "src/groundmap/tile_map.cpp", 
    "src/groundmap/tile_map_data.cpp", 
    
    "src/ai_manager.cpp", 
    "src/ai_vehicle.cpp", 
    "src/alist.cpp", 
    "src/ambulance.cpp", 
    "src/background.cpp", 
    "src/collision_manager.cpp", 
    "src/color.cpp", 
    "src/command_line_arguments.cpp", 
    "src/communication_dialog.cpp", 
    "src/controller_def.cpp", 
    "src/display/drawing_context.cpp", 
    "src/display/scene_context.cpp", 
    "src/display_manager.cpp", 
    "src/energie.cpp", 
    "src/explosion.cpp", 
    "src/feuerkraft.cpp", 
    "src/fonts.cpp", 
    "src/game_delta.cpp", 
    "src/game_mission.cpp", 
    "src/game_obj.cpp", 
    "src/game_obj_data_factory.cpp", 
    "src/game_obj_factory.cpp", 
    "src/game_obj_manager.cpp", 
    "src/game_session.cpp", 
    "src/game_session_manager.cpp", 
    "src/game_world.cpp", 
    "src/game_world_builder.cpp", 
    "src/game_world_data.cpp", 
    "src/globals.cpp", 
    "src/goal_manager.cpp", 
    "src/guile.cpp", 
    "src/help.cpp", 
    "src/ipc.cpp", 
    "src/keyboard_manager.cpp", 
    "src/keys.cpp", 
    "src/level_map.cpp", 
    "src/line_segments.cpp", 
    "src/marker.cpp", 
    "src/math.cpp", 
    "src/menu.cpp", 
    "src/menu_handle_mgr.cpp", 
    "src/menu_item.cpp", 
    "src/message_buffer.cpp", 
    "src/mine.cpp", 
    "src/output_world_builder.cpp", 
    "src/path_manager.cpp", 
    "src/player.cpp", 
    "src/player_view.cpp", 
    "src/projectile.cpp", 
    "src/property.cpp", 
    "src/property_set.cpp", 
    "src/radar.cpp", 
    "src/resource_manager.cpp", 
    "src/robot_tank.cpp", 
    "src/rocket.cpp", 
    "src/satchel_charge.cpp", 
    "src/scm_functor.cpp", 
    "src/scm_sequence_hook.cpp", 
    "src/screen.cpp", 
    "src/screenshot.cpp", 
    "src/sequence_manager.cpp", 
    "src/sexpr_world_reader.cpp", 
    "src/shockwave.cpp", 
    "src/soldier.cpp", 
    "src/soldier_ai.cpp", 
    "src/start_screen.cpp", 
    "src/system.cpp", 
    "src/tree.cpp", 
    "src/trigger_manager.cpp", 
    "src/unit.cpp", 
    "src/vector2d.cpp", 
    "src/vehicle_ai.cpp", 
    "src/vehicle_status.cpp", 
    "src/vehicle_view.cpp", 
    "src/view.cpp", 
    ])

# EOF #
